import Footer from '../../widgets/Footer/Footer'
import Navbar from '../../widgets/Navbar/Navbar'

import '../../globals.css'

export const metadata = {
	title: 'Aitim',
	description: 'Generated by create next app',
}

export default function Layout({ children }) {
	return (
		<>
			<Navbar />
			<>{children}</>
			<Footer />
		</>
	)
}
