import { Inter } from 'next/font/google'
import StoreProvider from './lib/Provider/StoreProvider'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Aitim',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<main className='relative overflow-hidden'>
					<StoreProvider>{children}</StoreProvider>
				</main>
			</body>
		</html>
	)
}
